CREATE TABLE ROLE (
    ID INT NOT NULL AUTO_INCREMENT,
    CODE VARCHAR(25) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    UNIQUE UNQ_CODE (CODE),
    PRIMARY KEY (ID)
);

CREATE TABLE USER (
    ID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(25) NOT NULL,
    PASSWORD VARCHAR(25) NOT NULL,
    ID_ROLE INT NOT NULL,
    UNIQUE UNQ_USERNAME (USERNAME),
    PRIMARY KEY (ID),
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (ID_ROLE) REFERENCES ROLE(ID)
);

CREATE TABLE PRODUCT (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(25) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    PRICE DECIMAL NOT NULL,
    POPULARITY INT DEFAULT 0,
    UNIQUE UNQ_NAME (NAME),
    PRIMARY KEY (ID)
);